### ISSUE TITLE
centos packages have a hard dependency on scl packages

### ISSUE THREAD

**Issue by attachmentgenie** [Icinga/rpm-icingaweb2#1]
due to https://github.com/Icinga/rpm-icingaweb2/blob/master/icingaweb2.spec#L40 the centos packages now have a hard dependency on the php packages that scl provides.

This is unwanted IMHO for 2 reasons, 1) not everybody wants to use the scl package but prefer to use other upstreams e.g. remi for their packages 2) the version of PHP provided by SCL are now either in their security updates only cycle (centos7 => 7.1) or are EOL outright ( centos 6 => 7.0). We need a way to install icingaweb using an upstream supported version of PHP

**Comment by lazyfrosch** [comment]
This has been discussed some time ago, please see the thread in https://github.com/Icinga/icinga-packaging/issues/69#issuecomment-353046514

We need to use OS supported versions...
