### ISSUE TITLE
Installation missing sclo-php71-php-pecl-imagick as dependancy

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/rpm-icingaweb2#2]
Whenn installing icingaweb2 via yum it install also rh-php71-php-fpm as dependancy, but misses sclo-php71-php-pecl-imagick package.

## Expected Behavior
Installing icingaweb2 from repository should install also all needed packages to run it.

## Current Behavior
Package sclo-php71-php-pecl-imagick is not installed as dependancy and needed to be installed manualy

## Possible Solution
Include it as dependancy

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.6.2
* Version used (`icinga2 --version`): r2.10.2-1
* Operating System and version: Centos 7.6.1810
* Enabled features (`icinga2 feature list`):
* Config validation (`icinga2 daemon -C`):
* If you run multiple Icinga 2 instances, the `zones.conf` file (or `icinga2 object list --type Endpoint` and `icinga2 object list --type Zone`) from all affected nodes.

**Comment by lazyfrosch** [comment]
SCLo is no official RedHat distribution, CentOS only:

https://wiki.centos.org/SpecialInterestGroup/SCLo

> <sclo> : The goal of prefix in the SCL name is *not* to scope or brand the software collection, rather it is to "namespace" it. Prefix "rh-" is used in case of Red Hat's collections available in Red Hat Software Collections product; or "sclo-" in case of collections created by the community.

As we can not use "recommended" packages in RHEL, we can't add it to the RPM...

But of course a user could install the package if so desired.
